### ISSUE TITLE
Test Spline-defined wells from the Model perspective

### ISSUE THREAD

**Issue by einar90** [PetroleumCyberneticsGroup/FieldOpt#36]
Write unit-tests for spline-defined wells in the Model-library.
- The class to be tested is Model::Wells::Wellbore::WellSpline
- The WellIndexCalculator should be considered as a "black box" in these tests.
- The spline is defined by two (x, y, z) points, and the class returns a set of well block objects (Model::Wells::Wellbore::WellBlock). The location of these ((i, j, k) coordinates) and the well index should be checked against data from RMS.
- Reservoir models (HORZWEL and 5Spot) are easily accessible through a TestResource.

**Comment by Bellout** [comment]
Very good!  M.

Sent from my Sony Xperia™ smartphone


---- Einar Baumann wrote ----


Write unit-tests for spline-defined wells in the Model-library.

  *   The class to be tested is Model::Wells::Wellbore::WellSpline
  *   The WellIndexCalculator should be considered as a "black box" in these tests.
  *   The spline is defined by two (x, y, z) points, and the class returns a set of well block objects (Model::Wells::Wellbore::WellBlock). The location of these ((i, j, k) coordinates) and the well index should be checked against data from RMS.
  *   Reservoir models (HORZWEL and 5Spot) are easily accessible through a TestResource.
