### ISSUE TITLE
error when trying to Make FieldOpt

### ISSUE THREAD

**Issue by hilmarm** [PetroleumCyberneticsGroup/FieldOpt#83]
I'm creating a Vagrant setup to spawn and automatically and provision a Virtual Machine (VM) for FieldOpt.
This will enable automatic provisioning (installing dependencies etc.), making the necessary libraries and copying the necessary files to where they belong.

However, at step 6. Build FieldOpt i ran in to the following error after running 'make' inside FieldOpt-build/

`[ 28%] Built target simulation_automoc
[ 34%] Built target runner
Scanning dependencies of target simulation
[ 34%] Building CXX object Simulation/CMakeFiles/simulation.dir/simulator_interfaces/adgprssimulator.cpp.o
In file included from /vagrant/FieldOpt/Simulation/simulator_interfaces/adgprssimulator.cpp:23:0:
/vagrant/FieldOpt/Simulation/results/adgprsresults.h:2:25: warning: missing terminating " character [enabled by default]
 #define ADGPRSRESULTS_HL"
                         ^
/vagrant/FieldOpt/Simulation/results/adgprsresults.h:2:25: warning: ISO C99 requires whitespace after the macro name [enabled by default]
[ 35%] Building CXX object Simulation/CMakeFiles/simulation.dir/results/adgprsresults.cpp.o
In file included from /vagrant/FieldOpt/Simulation/results/adgprsresults.cpp:1:0:
/vagrant/FieldOpt/Simulation/results/adgprsresults.h:2:25: warning: missing terminating " character [enabled by default]
 #define ADGPRSRESULTS_HL"
                         ^
/vagrant/FieldOpt/Simulation/results/adgprsresults.h:2:25: warning: ISO C99 requires whitespace after the macro name [enabled by default]
/vagrant/FieldOpt/Simulation/results/adgprsresults.cpp: In member function ‘virtual void Simulation::Results::AdgprsResults::ReadResults(QString)’:
/vagrant/FieldOpt/Simulation/results/adgprsresults.cpp:21:35: error: invalid use of incomplete type ‘class QStringList’
     if (file_path.split(".vars.h5").length() == 1)
                                   ^
In file included from /usr/include/qt5/QtCore/QString:1:0,
                 from /vagrant/FieldOpt/Simulation/results/results.h:4,
                 from /vagrant/FieldOpt/Simulation/results/adgprsresults.h:3,
                 from /vagrant/FieldOpt/Simulation/results/adgprsresults.cpp:1:
/usr/include/qt5/QtCore/qstring.h:81:7: error: forward declaration of ‘class QStringList’
 class QStringList;
       ^
make[2]: *** [Simulation/CMakeFiles/simulation.dir/results/adgprsresults.cpp.o] Error 1
make[1]: *** [Simulation/CMakeFiles/simulation.dir/all] Error 2
make: *** [all] Error 2
`
Any ideas on how to solve this? Looks like an issue when refering to a certain part of the Qt5 library.

**Comment by hilmarm** [comment]
Which compiler are you using? GCC version?

**Comment by einar90** [comment]
Fantastic idea! Sorry for the late reply. Day-to-day we're using the default version in Ubuntu 16.04, 5.4.0, but it also compiles on the most recent version in Arch (7.2.0). Which OS and Qt version are you using?

Please keep me updated on this if you're still working on it!

**Comment by hilmarm** [comment]
Running Ubuntu 16.04.3, for Qt I only do 'sudo apt install qt5-default'
