### ISSUE TITLE
Excessive amounts of memory spent

### ISSUE THREAD

**Issue by bragesk** [PetroleumCyberneticsGroup/FieldOpt#95]
During runs with multiple wells optimized, there is excessive utilization of memory. The memory usage scales with the number of wells, which suggest there is something in the Well Index Calculator that does not get deleted.

Had the same issue previously, in a previous version of the WIC. That was solved by adding a destructor

**Comment by einar90** [comment]
To help me pinpoint the root of the problem, could you try monitoring the memory when running with

 * Variable/non-variable well positions
 * Single/multiple realizations

With your "base case" and these other two, does the memory use increase with the number of iterations, or is it more or less constant?
